#!/bin/sh

### BEGIN INIT INFO
# Provides: gplayweb
# Required-Start: nginx
# Required-Stop:
# Should-Start:
# Default-Start: 2 3 4 5
# Default-Stop:
# Short-Description: Web interface for gplaycli
### END INIT INFO

. /lib/lsb/init-functions

PIDFILE=/tmp/gplayweb.pid
PROG_NAME=gplayweb
DAEMON=/usr/local/bin/gplayweb
LOGDIR=/var/log/gplayweb
LOGFILE=$LOGDIR/gplayweb.log
CONFFILE=/etc/gplayweb/gplayweb.conf
ARGUMENTS="-c $CONFFILE"
ANDROID_SDK=/opt/android-sdk-linux
USER=gplayweb
# See how we were called.
case "$1" in
  start)
        echo -n "Starting ${PROGRAM} ..."
        #### Commands to start the process running
        mkdir -p $LOGDIR
        start-stop-daemon --start -c $USER --quiet --pidfile $PIDFILE --exec /usr/bin/env ANDROID_HOME=$ANDROID_SDK $DAEMON & >$LOGFILE 2>&1 -- $ARGUMENTS
        sleep 1
        pgrep -fl $PROG_NAME | grep python | awk '{print $1}'  > $PIDFILE
        echo
        ;;  
  stop)
        echo -n "Shutting down $PROGRAM ..."
        kill -9 $(cat $PIDFILE)
        rm -f $PIDFILE
        echo
        ;;  
  status)
        status_of_proc -p $PIDFILE "$PROG_NAME" "gplayweb" && exit 0 || exit $?
        ;;  
  restart)
        $0 stop
        $0 start
        ;;  
  *)  
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
